title: Settings
fields:
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: has_animations
    field:
      type: toggle
      display: 'Animation Inhalte'
      default: true
  -
    import: theme_selector
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
